INSERT INTO plants (common_name, scientific_name, difficulty_level, toxicity_humans, toxicity_dogs, toxicity_cats, watering_info, light_requirement, climate_info, max_height_cm, leaf_type, planting_period)
VALUES
    ('Monstera', 'Monstera deliciosa', 'facile', 'Toxique si ingere', 'Toxique', 'Toxique', 'Arroser quand les 2-3 premiers cm de terre sont secs, environ 1 fois/semaine', 'Lumiere indirecte vive', 'Interieur, 18-27C, evite les courants d''air froid', 200, 'Feuille perforee persistante', 'Printemps a ete'),
    ('Marante (Prayer Plant)', 'Maranta leuconeura', 'modere', 'Non toxique', 'Non toxique', 'Non toxique', 'Garder le terreau legerement humide en permanence, eau non calcaire de preference (sensible au chlore)', 'Lumiere indirecte moderee', 'Interieur, 18-24C, humidite elevee requise ; les feuilles se replient le soir', 30, 'Feuille ovale marbree a motif distinctif', 'Printemps'),
    ('Pilea (plante à monnaie chinoise)', 'Pilea peperomioides', 'facile', 'Non toxique', 'Non toxique', 'Non toxique', 'Arroser quand les 2-3 premiers cm de terre sont secs, environ 1 fois/semaine ; tourner le pot regulierement pour une croissance uniforme', 'Lumiere indirecte vive', 'Interieur, 15-24C, evite le plein soleil direct qui brule les feuilles', 30, 'Feuille ronde plate et charnue', 'Toute l''annee'),
    ('Caoutchouc (Ficus)', 'Ficus elastica', 'facile', 'Legerement toxique (seve irritante)', 'Toxique', 'Toxique', 'Arroser quand la surface est seche, environ 1 fois/semaine', 'Lumiere indirecte vive', 'Interieur, 18-27C, sensible aux courants d''air froid', 250, 'Grande feuille brillante et epaisse', 'Printemps a ete'),
    ('Aloe vera', 'Aloe vera', 'facile', 'Peut irriter en cas d''ingestion', 'Toxique', 'Toxique', 'Arroser abondamment puis laisser secher completement, toutes les 2-3 semaines', 'Forte lumiere directe', 'Interieur/exterieur, 13-27C, aime la chaleur seche', 60, 'Feuille charnue succulente', 'Printemps a ete'),
    ('Calathea rayée', 'Calathea lancifolia', 'difficile', 'Non toxique', 'Non toxique', 'Non toxique', 'Garder le terreau legerement humide en permanence, eau non calcaire de preference', 'Lumiere indirecte moderee', 'Interieur, 18-24C, humidite elevee requise', 90, 'Feuille rayee decorative', 'Printemps'),
    ('ZZ Plant', 'Zamioculcas zamiifolia', 'facile', 'Toxique si ingere', 'Toxique', 'Toxique', 'Arroser toutes les 2-3 semaines, tres tolerant a l''oubli', 'Faible a moderee', 'Interieur, 18-26C, tres tolerant', 90, 'Feuille brillante charnue', 'Toute l''annee'),
    ('Cactus de Noël', 'Schlumbergera bridgesii', 'facile', 'Non toxique', 'Non toxique', 'Non toxique', 'Arroser quand le terreau est sec en surface, reduire en hiver', 'Lumiere indirecte vive', 'Interieur, 15-24C', 40, 'Tige segmentee succulente', 'Automne (floraison hiver)'),
    ('Violette africaine', 'Saintpaulia ionantha', 'modere', 'Non toxique', 'Non toxique', 'Non toxique', 'Arroser par le bas pour eviter de mouiller les feuilles, garder legerement humide', 'Lumiere indirecte vive', 'Interieur, 18-24C, humidite moderee', 30, 'Feuille duveteuse ronde', 'Toute l''annee'),
    ('Dieffenbachia (canne muette)', 'Dieffenbachia seguine', 'modere', 'Toxique si ingere (irritant buccal)', 'Toxique', 'Toxique', 'Arroser quand la surface est seche, eviter l''exces d''eau', 'Lumiere indirecte moderee', 'Interieur, 18-27C, humidite moderee', 150, 'Grande feuille panachee', 'Printemps a ete'),
    ('Fougère de Boston', 'Nephrolepis exaltata', 'modere', 'Non toxique', 'Non toxique', 'Non toxique', 'Garder le terreau constamment humide, brumiser regulierement', 'Lumiere indirecte moderee', 'Interieur, 16-24C, humidite elevee', 90, 'Feuille dentelee retombante', 'Printemps'),
    ('Muguet', 'Convallaria majalis', 'facile', 'Tres toxique si ingere (toute la plante)', 'Tres toxique', 'Tres toxique', 'Garder le sol humide en permanence, surtout pendant la floraison', 'Ombre partielle a lumiere indirecte', 'Exterieur/interieur, 10-20C, plante vivace rustique preferant la fraicheur', 25, 'Feuille lanceolee, petites fleurs blanches en clochettes parfumees', 'Automne (plantation), floraison au printemps'),
    ('Arbre de jade (Crassula)', 'Crassula ovata', 'facile', 'Legerement toxique si ingere', 'Toxique', 'Toxique', 'Arroser abondamment puis laisser secher completement, toutes les 2-3 semaines, tres tolerant a la secheresse', 'Forte lumiere directe', 'Interieur, 15-24C, aime la lumiere vive et un peu de fraicheur en hiver', 90, 'Feuille charnue ovale brillante', 'Printemps a ete'),
    ('Anthurium', 'Anthurium andraeanum', 'modere', 'Toxique si ingere', 'Toxique', 'Toxique', 'Arroser quand la surface est seche, eviter l''exces d''eau', 'Lumiere indirecte vive', 'Interieur, 18-27C, humidite elevee', 60, 'Feuille brillante en coeur', 'Toute l''annee'),
    ('Palmier nain (Parlor Palm)', 'Chamaedorea elegans', 'facile', 'Non toxique', 'Non toxique', 'Non toxique', 'Garder le terreau legerement humide, ne pas laisser secher completement', 'Lumiere faible a moderee', 'Interieur, 18-27C, humidite moderee', 120, 'Feuille pennee fine', 'Printemps')
ON CONFLICT (scientific_name) DO NOTHING;